name_experiment: test

datamodule:
  path_df_train: /home/ec2-user/repo/team_b/datasets/df_train.csv
  path_df_val: /home/ec2-user/repo/team_b/datasets/df_val.csv
  path_df_test: /home/ec2-user/repo/team_b/datasets/df_test.csv
  path_df_predict: /home/ec2-user/repo/team_b/datasets/df_val.csv
  train_ratio: 0.8
  batch_size: 16
  num_workers: 2
  sampler: imbalanced_dataset_sampler
  selected_categories: null
  save_dfs: True

model:
  input_shape: [3, 224, 224]

pretrained_model:
  input_shape: [3, 224, 224]
  torch_model: resnet18
  pretrained: True
  train_all_params: True

lit_model:
  learning_rate: 0.0001
  loss: null
  optimizer: null
  use_torch_model: True

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 100
  fast_dev_run: False
  gpus: [0]

tensorboard_logs:
  save_dir: .
  name: first_run

checkpoint_callback:
  monitor: val/loss
  mode: min
  save_last: True
  filename: best-checkpoint

checkpoint_path: null #path to checkpoint
